### ISSUE TITLE
Build issue.

### ISSUE THREAD

**Issue by fdsamxn** [AndrewRichards-Code/GEAR#2]
Hi, Im using VS2019, when I compile the entire project I got this error, 
`
Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Microsoft\VC\v160\Microsoft.CppBuild.targets(439,5): error MSB8020: The build tools for v142 (Platform Toolset = 'v142') cannot be found.
`
However I have "build tools for v142 " installed, maybe I downloaded wrong one, could you tell which one should I download.
Thank you.

**Comment by AndrewRichards-Code** [comment]
Hi,
Thank you for raising this issue. Visual Studio 2019 comes by default with the MSVC v142 build tools. You can check for 'MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest)' in the Individual Components section of the Visual Studio Installer application. Further to this, you can check whether the v142 build tools are installed by going to the Property Page of any project and looking under Configuration Properties->General->Platform Toolset to confirm which toolsets are available/being used.

I hope this help. Best Wishes,
Andrew

**Comment by fdsamxn** [comment]
Hi Dear Andrew.
I have MSVC v142 - VS 2019 C++ x64/x86 build tools (Latest) installed and configured when I submiting this error. 
Yes, I know this sounds a bit strange, anyway Thank you for the help.
I will check the code structure. 
Thx :)

**Comment by AndrewRichards-Code** [comment]
Hi,

Thank you for the update. I have looked into this a little further. 
This might be relevant, if you are trying to build Gaming.Desktop.x64 without the Public GDK installed:  https://github.com/microsoft/DirectX-Graphics-Samples/issues/698

Thank you once again,
Andrew

**Comment by fdsamxn** [comment]
> Hi,
> 
> Thank you for the update. I have looked into this a little further. This might be relevant, if you are trying to build Gaming.Desktop.x64 without the Public GDK installed: [microsoft/DirectX-Graphics-Samples#698](https://github.com/microsoft/DirectX-Graphics-Samples/issues/698)
> 
> Thank you once again, Andrew

Hi Andrew.
Thank for the effort you make to make this solution run in my computer, I still got the same error and when I download GDK installer I got error instalation :).
I will check your code structre because all the codes are well divided is different solution.
Thx you once again 👍 .
